name: deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  run:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Move all files that should be uploaded to a new directory
      - run: mkdir ${{ github.event.repository.name }}-build && rsync -a --exclude-from='.github/exclude_list' . ${{ github.event.repository.name }}-build
      - run: cd ${{ github.event.repository.name }}-build && zip -r ../${{ github.event.repository.name }}.zip * -x "${{ github.event.repository.name }}-build/*" && cd ..
      - run: rm -rf ${{ github.event.repository.name }}-build
      # Create release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}.zip
          name: Release ${{ github.ref_name }}
  # Attach to artifacts
  download:
    name: Download Artifacts
    needs: [run]
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.zip
